# Generated by Django 5.2.6 on 2025-09-08 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('ball', 'Football'), ('accessories', 'Accessories'), ('training', 'Training Equipment')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
